# Generated by Django 4.0.2 on 2022-02-25 23:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0014_remove_student_cv_remove_student_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Program',
            new_name='Program_staff',
        ),
    ]
