# Generated by Django 4.0.2 on 2022-02-26 00:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0017_alter_company_companyname_company_mentor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company_companyRepresentive',
            new_name='Company_companyRepresentative',
        ),
    ]
