# Generated by Django 4.0.2 on 2022-02-26 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rename_company_companyrepresentive_company_companyrepresentative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='mentor',
        ),
    ]
