# Generated by Django 4.0.2 on 2022-02-26 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_company_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
    ]
