# Generated by Django 4.0.2 on 2022-02-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_company_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(default='candidate', editable=False, max_length=100),
        ),
    ]
