# Generated by Django 4.0.2 on 2022-02-25 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internships',
            name='about',
        ),
        migrations.RemoveField(
            model_name='internships',
            name='companyName',
        ),
        migrations.RemoveField(
            model_name='internships',
            name='program',
        ),
        migrations.RemoveField(
            model_name='internships',
            name='requirements',
        ),
    ]
