# Generated by Django 4.0.2 on 2022-02-26 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_remove_program_id_program_department_and_more'),
        ('users', '0019_remove_company_mentor'),
        ('internships', '0003_internships_about_internships_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internships',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='internships',
            name='companyRepresentative',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.company_companyrepresentative'),
        ),
        migrations.AddField(
            model_name='internships',
            name='mentor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.company_mentor'),
        ),
        migrations.AddField(
            model_name='internships',
            name='program',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='program.program'),
        ),
    ]
