# Generated by Django 4.0.2 on 2022-02-26 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_company_user'),
        ('internships', '0004_internships_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internships',
            name='internshipName',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='internships',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company_mentor'),
        ),
    ]
