# Generated by Django 4.0.2 on 2022-02-26 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_student_status'),
        ('internships', '0005_alter_internships_internshipname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentIntern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='internships',
            name='isAssign',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='HoursReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('status', models.CharField(default='not approved', max_length=100)),
                ('intern', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='internships.assignmentintern')),
            ],
        ),
        migrations.AddField(
            model_name='assignmentintern',
            name='internship',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='internships.internships'),
        ),
        migrations.AddField(
            model_name='assignmentintern',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
    ]
