# Generated by Django 4.0.2 on 2022-02-26 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_alter_program_department_alter_program_semester'),
        ('users', '0022_alter_student_status'),
        ('internships', '0006_assignmentintern_internships_isassign_hoursreport_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Internships',
            new_name='Internship',
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_decision_by_company', models.CharField(default='not accepted', max_length=100)),
                ('status_decision_by_program_manager', models.CharField(default='not accepted', max_length=100)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internships.internship')),
            ],
        ),
    ]
