# Generated by Django 4.0.2 on 2022-02-25 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_programcoordinator_programmanager_and_more'),
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='id',
        ),
        migrations.AddField(
            model_name='program',
            name='department',
            field=models.CharField(default='A', max_length=5),
        ),
        migrations.AddField(
            model_name='program',
            name='semester',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='program',
            name='year',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='program',
            field=models.CharField(max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='programCoordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.programcoordinator'),
        ),
        migrations.AlterField(
            model_name='program',
            name='programManager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.programmanager'),
        ),
    ]
