# Generated by Django 4.0.2 on 2022-02-27 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='programCoordinator',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='user.programcoordinator'),
        ),
        migrations.AddField(
            model_name='program',
            name='programManager',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='user.programmanager'),
        ),
    ]
