# Generated by Django 4.0.2 on 2022-02-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_remove_program_id_program_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='department',
            field=models.CharField(default='A', max_length=100),
        ),
        migrations.AlterField(
            model_name='program',
            name='semester',
            field=models.CharField(default='A', max_length=2),
        ),
    ]
