# Generated by Django 4.0.2 on 2022-03-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_program_programcoordinator_program_programmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='semester',
            field=models.CharField(default='A', max_length=4),
        ),
        migrations.AlterField(
            model_name='program',
            name='year',
            field=models.CharField(default='2020', max_length=4),
        ),
    ]
