# Generated by Django 4.0.2 on 2022-03-04 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('program', '0003_alter_program_semester_alter_program_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='hoursRequired',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='program',
            name='prioritiesAmount',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='program',
            name='program',
            field=models.CharField(default='2020', max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='program',
            name='programCoordinator',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.programcoordinator'),
        ),
        migrations.AlterField(
            model_name='program',
            name='programManager',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.programmanager'),
        ),
    ]
