# Generated by Django 4.0.2 on 2022-03-11 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_student_status'),
        ('program', '0005_alter_program_programmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='programManager',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.programmanager'),
        ),
    ]
