# Generated by Django 4.0.2 on 2022-03-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_alter_program_programmanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='programCoordinator',
        ),
        migrations.RemoveField(
            model_name='program',
            name='programManager',
        ),
        migrations.AddField(
            model_name='program',
            name='status',
            field=models.CharField(default='True', max_length=4),
        ),
    ]
