# Generated by Django 4.0.2 on 2022-03-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0007_remove_program_programcoordinator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='status',
            field=models.CharField(default='True', max_length=6),
        ),
    ]
