# Generated by Django 4.0.2 on 2022-03-11 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_student_status'),
        ('program', '0010_studentandprogrammanager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentAndProgramManager',
            new_name='ProgramManagerAndProgram',
        ),
        migrations.RenameField(
            model_name='programmanagerandprogram',
            old_name='student',
            new_name='programManager',
        ),
    ]
