# Generated by Django 4.0.2 on 2022-03-11 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_student_status'),
        ('program', '0012_companyrepresentativeandprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMentorAndProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyMentor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.companymentor')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.program')),
            ],
        ),
    ]
