# Generated by Django 4.0.3 on 2022-06-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0015_alter_companymentorandprogram_companymentor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='status',
            field=models.CharField(default='False', max_length=6),
        ),
    ]
