# Generated by Django 4.0.2 on 2022-02-27 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('program', '0002_program_programcoordinator_program_programmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentIntern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('internshipName', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('about', models.TextField(default='')),
                ('requirements', models.TextField(default='')),
                ('isAssign', models.BooleanField(default=False)),
                ('companyName', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.company')),
                ('companyRepresentative', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.companyrepresentative')),
                ('mentor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.companymentor')),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='program.program')),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_decision_by_company', models.CharField(default='not accepted', max_length=100)),
                ('status_decision_by_program_manager', models.CharField(default='not accepted', max_length=100)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.internship')),
            ],
        ),
        migrations.CreateModel(
            name='HoursReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('status', models.CharField(default='not approved', max_length=100)),
                ('intern', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='internship.assignmentintern')),
                ('mentor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.companymentor')),
                ('student', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='user.student')),
            ],
        ),
        migrations.AddField(
            model_name='assignmentintern',
            name='internship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.internship'),
        ),
        migrations.AddField(
            model_name='assignmentintern',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student'),
        ),
    ]
