# Generated by Django 4.0.2 on 2022-03-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='student_priority_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
