# Generated by Django 4.0.2 on 2022-03-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_priority_student_priority_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoursreport',
            name='date',
            field=models.CharField(default='1.1.2020', max_length=20),
        ),
        migrations.AlterField(
            model_name='hoursreport',
            name='endTime',
            field=models.CharField(default='20:00:00', max_length=20),
        ),
        migrations.AlterField(
            model_name='hoursreport',
            name='startTime',
            field=models.CharField(default='08:00:00', max_length=20),
        ),
    ]
