# Generated by Django 4.0.2 on 2022-03-04 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0004_rename_intern_hoursreport_internship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentintern',
            name='internship',
        ),
        migrations.RemoveField(
            model_name='hoursreport',
            name='internship',
        ),
        migrations.RemoveField(
            model_name='priority',
            name='internship',
        ),
    ]
