# Generated by Django 4.0.2 on 2022-03-04 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0005_remove_assignmentintern_internship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoursreport',
            name='internship',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='internship.assignmentintern'),
        ),
    ]
