# Generated by Django 4.0.2 on 2022-03-05 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_alter_program_programmanager'),
        ('internship', '0007_assignmentintern_internship'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='internship',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='internship.internship'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='internshipName',
            field=models.CharField(default='2020', max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='internship',
            name='program',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='program.program'),
        ),
    ]
