# Generated by Django 4.0.2 on 2022-03-05 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0009_remove_priority_internship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='internship',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='internship.internship'),
        ),
    ]
