# Generated by Django 4.0.2 on 2022-03-12 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0010_priority_internship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='companyRepresentative',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='mentor',
        ),
    ]
