# Generated by Django 4.0.2 on 2022-03-12 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_systemmanager'),
        ('internship', '0011_remove_internship_companyrepresentative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='companyRepresentative',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.companyrepresentative'),
        ),
    ]
