# Generated by Django 4.0.2 on 2022-03-12 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0012_internship_companyrepresentative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='companyRepresentative',
        ),
    ]
