# Generated by Django 4.0.2 on 2022-03-13 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0014_programcoordinatorandprogram'),
        ('internship', '0013_remove_internship_companyrepresentative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='program',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='program.program'),
        ),
    ]
