# Generated by Django 4.0.3 on 2022-03-20 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_systemmanager'),
        ('program', '0014_programcoordinatorandprogram'),
        ('internship', '0014_alter_internship_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internshipName', models.CharField(default='', max_length=120)),
                ('about', models.TextField(default='')),
                ('requirements', models.TextField(default='')),
                ('isAssign', models.BooleanField(default=False)),
                ('companyName', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.company')),
                ('program', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='program.program')),
            ],
        ),
    ]
