# Generated by Django 4.0.3 on 2022-03-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0015_internshipdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InternshipDetails',
        ),
    ]
