# Generated by Django 4.0.3 on 2022-03-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0017_internshipdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipdetails',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
