# Generated by Django 4.0.3 on 2022-03-24 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0018_internshipdetails_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentintern',
            name='internship',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='internship.internshipdetails'),
        ),
        migrations.AlterField(
            model_name='priority',
            name='internship',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='internship.internshipdetails'),
        ),
    ]
