# Generated by Django 4.0.3 on 2022-03-24 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0019_alter_assignmentintern_internship_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Internship',
        ),
    ]
