# Generated by Django 4.0.3 on 2022-03-26 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0021_alter_hoursreport_mentor_alter_hoursreport_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoursreport',
            name='internship',
        ),
        migrations.RemoveField(
            model_name='hoursreport',
            name='mentor',
        ),
    ]
