# Generated by Django 4.0.3 on 2022-03-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0022_remove_hoursreport_internship_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoursreport',
            name='status',
        ),
        migrations.AddField(
            model_name='hoursreport',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
