# Generated by Django 4.0.3 on 2022-03-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0023_remove_hoursreport_status_hoursreport_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoursreport',
            name='totalTime',
            field=models.IntegerField(default=0),
        ),
    ]
