# Generated by Django 4.0.3 on 2022-03-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0024_hoursreport_totaltime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoursreport',
            name='totalTime',
            field=models.FloatField(default=0.0),
        ),
    ]
