# Generated by Django 4.0.3 on 2022-03-26 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_student_status'),
        ('internship', '0025_alter_hoursreport_totaltime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='status_decision_by_company',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AlterField(
            model_name='priority',
            name='status_decision_by_program_manager',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.CreateModel(
            name='InternshipAndMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='internship.internshipdetails')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.companymentor')),
            ],
        ),
    ]
