# Generated by Django 4.0.3 on 2022-04-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0028_rename_inter_internshipandintern_intern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoursreport',
            name='totalTime',
            field=models.CharField(default='20:00:00', max_length=20),
        ),
    ]
