# Generated by Django 4.0.3 on 2022-04-23 08:40

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_student_status'),
        ('internship', '0029_alter_hoursreport_totaltime'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportByMentor', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='./data/'), upload_to='C:\\Users\\USER\\Desktop\\Yuval\\bgu\\backend\\ims_server\\data\reportByMentor', verbose_name='reportByMentor')),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.companymentor')),
            ],
        ),
        migrations.CreateModel(
            name='InternReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='./data/'), upload_to='C:\\Users\\USER\\Desktop\\Yuval\\bgu\\backend\\ims_server\\data\reportByStudent', verbose_name='reportByStudent')),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
            ],
        ),
    ]
