# Generated by Django 4.0.3 on 2022-04-23 11:05

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0030_mentorreport_internreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorreport',
            name='reportByMentor',
        ),
        migrations.AddField(
            model_name='mentorreport',
            name='report',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='./data/'), upload_to='C:\\Users\\USER\\Desktop\\Yuval\\bgu\\backend\\ims_server\\data/reportByMentor', verbose_name='reportByMentor'),
        ),
        migrations.AlterField(
            model_name='internreport',
            name='report',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='./data/'), upload_to='C:\\Users\\USER\\Desktop\\Yuval\\bgu\\backend\\ims_server\\data/reportByStudent', verbose_name='reportByStudent'),
        ),
    ]
