# Generated by Django 4.0.2 on 2022-03-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_companyrepresentative_companyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(default='student', max_length=100),
        ),
    ]
