# Generated by Django 4.0.2 on 2022-03-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='companyName',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='about',
            field=models.CharField(blank=True, max_length=500, primary_key=True, serialize=False),
        ),
    ]
