# Generated by Django 4.0.3 on 2022-04-21 10:29

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0002_remove_companyprofile_companyname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='username',
            new_name='student_id',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='photo',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='picture',
            field=models.FileField(blank=True, max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(location='./data/'), upload_to='C:\\Users\\USER\\Desktop\\Yuval\\bgu\\backend\\ims_server\\<django.db.models.fields.related.ForeignKey>\\data\\images', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='birthdate',
            field=models.CharField(default='21.12.1993', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='./data/'), upload_to='C:\\Users\\USER\\Desktop\\Yuval\\bgu\\backend\\ims_server\\<django.db.models.fields.related.ForeignKey>\\data\\cv', verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gradesSheet',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='./data/'), upload_to='C:\\Users\\USER\\Desktop\\Yuval\\bgu\\backend\\ims_server\\<django.db.models.fields.related.ForeignKey>\\data\\gradesSheet', verbose_name='Grades Sheet'),
        ),
    ]
