# Generated by Django 4.0.3 on 2022-04-21 10:41

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0003_rename_username_studentprofile_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='./data/'), upload_to='C:\\Users\\USER\\Desktop\\Yuval\\bgu\\backend\\ims_server\\data\\cv', verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gradesSheet',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='./data/'), upload_to='C:\\Users\\USER\\Desktop\\Yuval\\bgu\\backend\\ims_server\\data\\gradesSheet', verbose_name='Grades Sheet'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='picture',
            field=models.FileField(blank=True, max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(location='./data/'), upload_to='C:\\Users\\USER\\Desktop\\Yuval\\bgu\\backend\\ims_server\\data\\images', verbose_name='Profile Picture'),
        ),
    ]
