# Generated by Django 4.0.3 on 2022-04-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0004_alter_studentprofile_cv_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='student_id',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='birthdate',
            field=models.CharField(default='10.10.2010', max_length=20),
        ),
    ]
