# Generated by Django 4.0.3 on 2022-06-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0007_companyprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='company',
            new_name='companyName',
        ),
    ]
