# Generated by Django 4.0.3 on 2022-06-08 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_student_status'),
        ('profile_user', '0008_rename_company_companyprofile_companyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='companyName',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.company'),
        ),
    ]
