# Generated by Django 4.0.2 on 2022-02-26 16:21

import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0020_remove_company_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=10)),
                ('birthdate', models.DateTimeField(auto_now_add=True)),
                ('gitLink', models.URLField(blank=True)),
                ('linkedinLink', models.URLField(blank=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('photo', models.FileField(blank=True, max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(location='./data/'), upload_to='C:\\Users\\USER\\Desktop\\Yuval\\bgu\\backend\\ims_server\\data\\images', verbose_name='Profile Picture')),
                ('cv', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='./data/'), upload_to='C:\\Users\\USER\\Desktop\\Yuval\\bgu\\backend\\ims_server\\data\\cv', verbose_name='CV')),
                ('gradesSheet', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='./data/'), upload_to='C:\\Users\\USER\\Desktop\\Yuval\\bgu\\backend\\ims_server\\data\\gradesSheet', verbose_name='CV')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearEstablish', models.PositiveIntegerField(blank=True, help_text='Use the following format: <YYYY>', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2022)])),
                ('workersAmount', models.PositiveIntegerField(blank=True, default=1)),
                ('linkedinLink', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('about', models.CharField(blank=True, max_length=500)),
                ('companyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
            ],
        ),
    ]
